### ISSUE TITLE
global_ignore_columns config not working

### ISSUE THREAD

**Issue by florinutz** [simplethings/EntityAudit#135]
I would like to use this config

```
simple_things_entity_audit:
    global_ignore_columns:
        - created_at
        - updated_at
        - deleted_at
        - created_by
        - updated_by
        - deleted_by
```

(would have been nice to be able to customise ignored columns per entity btw)

But global_ignore_columns doesn't work, all the columns are duplicated.

Is there any way around this?

**Comment by krossroad** [comment]
Having same problem. 'global_ignore_columns' are not working.

**Comment by OskarStark** [comment]
fieldnames are correct

created_at != createdAt

**Comment by StrikeForceZero** [comment]
I was confused by this as well until I logged the value of [$changeset](https://github.com/simplethings/EntityAudit/blob/v0.7/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php#L111) and saw that my properties were in camelCase but snake_case in the table. Maybe adding a check against a snake_case converted property would be a good idea?

**Comment by peschee** [comment]
A more suitable name for the configuration entry would probably be `global_ignore_fields` since the changeset returned in https://github.com/simplethings/EntityAudit/blob/master/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php#L191contains the entity field names, not the database table column names.
