### ISSUE TITLE
Many-To-Many associations are NOT versioned

### ISSUE THREAD

**Issue by 0x68** [simplethings/EntityAudit#161]
Hi everybody, 

i'm wondering why this TODO is left, i'm currently diving deeper in to Doctrine and Symfony2 and have currently the problem to solve the audit of all my entities which includes also the n to m relations.

Could anybody give me an advise how to solve this within this Bunde  ?

Thx in Advance

**Comment by soerenbernstein** [comment]
I would like to see this feature too.

**Comment by peschee** [comment]
Is this bundle alive @DavidBadura? Have there been discussions about adding this?

**Comment by tolry** [comment]
@peschee we do not have any active maintainers with good knowledge of the codebase, unfortunately. This extension was created for one small project of ours which is still alive and well. But since that project is a simple use case and we haven't had use for the extension in other projects, knowledge isn't what it could be. Since the creator of the extension is no longer involved in the development, all knowledge is second hand anyways.

I have been meaning to give a heads up in the README about this, but haven't gotten around to it yet. Anyone around who has experience in transitioning a project to a new maintainer or any suggestions on finding new maintainers are very welcome.

**Comment by peschee** [comment]
I see, thanks for the writeup. We are currently considering using this audit bundle for a project instead of writing the audit functionality from scratch.

As of now, we don't have Many-To-Many relationships. I just wanted to know while evaluating, if that feature is available or not. The {{README}} states Many-To-Many is unsupported. However, looking at #99 it seems implemented.

Should we miss something during our implementation, we'll try to add it back to the bundle. As for the project transition. I cannot give a helping hand there, since that is not something we've done either.

**Comment by DavidBadura** [comment]
I have the README updated
