### ISSUE TITLE
audited_entities configured but not used

### ISSUE THREAD

**Issue by Jerome1337** [simplethings/EntityAudit#199]
I'm using this bundle with the Symfony 2.8 app and Doctrine ORM 2.5
I have install, enable and configure this bundle with the entities I want to audit.

```
# SimpleThings Entity Audit
simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\User
        - AppBundle\Entity\Server
        - AppBundle\Entity\IpV4
        - AppBundle\Entity\IpV6
        - AppBundle\Entity\Purchase
```

The bundle should now only audit this entities and create only 6 tables (for this 5 entities and the revisions table).

But when I use `./app/console doctrine:schema:update --force` this create `_audit` tables for every single table of my database.

Did I forget something or this is a common bug ?

**Comment by bendavies** [comment]
@Jerome1337 I can't replicate this. There is code in the schema listener to prevent against this:
https://github.com/simplethings/EntityAudit/blob/2d8de80e851cdac1071f54fd710bad4b7ae84f51/src/SimpleThings/EntityAudit/EventListener/CreateSchemaListener.php#L60-L76

Can you please reopen this if you can see what the issue is, but i'm going to close for now.

**Comment by ceesvanegmond** [comment]
@Jerome1337 Do you solved the problem. I'm having the exact same problem @bendavies. Currently investigating...

**Comment by ceesvanegmond** [comment]
@bendavies Found the problem, problem occurs when using Sonata Admin. Do you have this code enabled? This should solve it.

```yml
sonata_doctrine_orm_admin:
    audit:
        force: false
```

**Comment by Jerome1337** [comment]
@ceesvanegmond Exactly this solve the creation problem.
